export const CONTENT_TYPE_QUESTION = "QUESTION";
export const CONTENT_TYPE_ARTICLE = "ARTICLE"
export const CONTENT_TYPE_USER = "My Content"
export const FILTER_CRITERIA_ASCENDING = "ASCENDING";
export const FILTER_CRITERIA_DESCENDING = "DESCENDING";